/**
 * Field labels aligned with HRM Satyakabir reference UI.
 * Use these in HRM pages and admin employee forms for consistent naming.
 */

export const LEGACY_EMPLOYEE_LABELS = {
  firstName: "First name",
  lastName: "Last name",
  gender: "Gender",
  joiningDate: "Joining date",
  exitDate: "Exit date",
  email: "Email",
  phone: "Phone",
  employeeId: "Employee ID",
  password: "Password",
  newPassword: "New password (optional)",
  designation: "Designation",
  department: "Department",
  accessRole: "Access role",
  position: "Position",
  employmentType: "Employment type",
  status: "Status",
  basicSalary: "Basic",
  allowances: "Allowances",
  deductions: "Deductions",
  netSalary: "Net salary",
  paidLeaveDaysPerMonth: "Paid leave days / month",
  lateDeductionRate: "Late deduction rate (%)",
  maxWfhDaysPerMonth: "Max WFH days / month",
  dob: "Date of birth",
  bloodGroup: "Blood group",
  maritalStatus: "Marital status",
  bio: "Bio",
  adharNumber: "Adhar number",
  panNumber: "PAN",
  linkedin: "Linkedin",
  githubId: "GitHub ID",
  twitter: "Twitter",
  facebook: "Facebook",
  instagram: "Instagram",
  website: "Website",
  accountHolderName: "Account holder name",
  accountNumber: "Account number",
  bankName: "Bank name",
  branchName: "Branch",
  ifsc: "IFSC",
  emergencyContactName: "Name",
  emergencyContactRelation: "Relation",
  emergencyContactPhone: "Phone",
  emergencyContactEmail: "Email",
  teamLeader: "Team leader",
  reportingManager: "Reporting manager",
  shiftTemplate: "Shift template",
  probationEndDate: "Probation end",
  currentAddress: "Current address",
  permanentAddress: "Permanent address",
  street: "Street address",
  city: "City",
  state: "State / Province",
  country: "Country",
  zipCode: "ZIP / Postal code",
} as const;

export const LEGACY_LEAVE_LABELS = {
  dialogTitle: "Apply for leave",
  dialogDescription: "Submit a request to HR. You will be notified once it is approved or rejected.",
  adminDialogTitle: "Apply leave for employee",
  adminDialogDescription:
    "Record leave on behalf of an employee. The request enters the normal approval queue unless you approve it separately.",
  employee: "Employee",
  leaveType: "Leave type",
  duration: "Duration",
  startDate: "Start date",
  endDate: "End date",
  halfDayPart: "Half day session",
  shortLeaveHours: "Hours",
  contactPhone: "Contact phone (optional)",
  reason: "Reason",
  submit: "Submit request",
  adminSubmit: "Submit for employee",
  durationFull: "Full day",
  durationHalf: "Half day",
  durationShort: "Short leave (hours)",
  halfFirst: "First half",
  halfSecond: "Second half",
} as const;

export const LEGACY_WFH_LABELS = {
  dialogTitle: "Request work from home",
  startDate: "Start date",
  endDate: "End date",
  reason: "Reason",
  contactPhone: "Contact phone (optional)",
  submit: "Submit WFH request",
} as const;

export const LEGACY_PAYROLL_LABELS = {
  basic: "Basic",
  hra: "HRA",
  allowances: "Allowances",
  pfEmployee: "PF (employee)",
  pfEmployer: "PF (employer)",
  tds: "TDS",
  bankName: "Bank name",
  accountNumber: "Account number",
  ifsc: "IFSC",
  pan: "PAN",
  grossSalary: "Gross salary",
  netPay: "Net pay",
  employee: "Employee",
  saveStructure: "Save structure",
  structuresTitle: "Salary structures",
} as const;

export const LEGACY_SETTINGS_LABELS = {
  attendancePolicy: "Attendance policy",
  globalWfhMode: "Global WFH mode",
  globalWfhHint: "Everyone works remotely — clock in to mark WFH; no office geofence. Shift punctuality still applies (late penalties are enforced).",
  shortfallThreshold: "Grace period (minutes)",
  maxFreeLates: "Free late days / month",
  electronOnlyClock: "Electron-only clock",
  leavePolicy: "Leave policy",
  paidLeavesPerMonth: "Paid leaves per month (default)",
  leaveResetCycleMonths: "Leave balance reset cycle (months)",
  carryForwardStartYear: "Carry-forward start year (other leave types)",
  leaveYearStartMonth: "Leave year start month",
  weekendDays: "Weekend days",
  defaultShift: "Default shift template",
  save: "Save settings",
} as const;

export const LEGACY_CORRECTION_LABELS = {
  dialogTitle: "Request attendance correction",
  date: "Date",
  requestType: "Request type",
  correctedStatus: "Corrected status",
  correctedMinutes: "Corrected active minutes",
  reason: "Reason / remarks",
  submit: "Submit correction",
  types: {
    missed_clock_in: "Missed clock in",
    missed_clock_out: "Missed clock out",
    wrong_time: "Wrong time entry",
    full_day: "Full day correction",
  } as const,
} as const;

export const LEGACY_ATTENDANCE_STATUS_OPTIONS = [
  { value: "present", label: "Present" },
  { value: "absent", label: "Absent" },
  { value: "on_leave", label: "On leave" },
  { value: "onsite", label: "Onsite" },
  { value: "wfh", label: "WFH" },
  { value: "half_day", label: "Half day" },
] as const;

export const LEGACY_WEEKDAY_OPTIONS = [
  { value: 0, label: "Sunday" },
  { value: 1, label: "Monday" },
  { value: 2, label: "Tuesday" },
  { value: 3, label: "Wednesday" },
  { value: 4, label: "Thursday" },
  { value: 5, label: "Friday" },
  { value: 6, label: "Saturday" },
] as const;

export const LEGACY_LEAVE_YEAR_MONTHS = [
  { value: 1, label: "January" },
  { value: 2, label: "February" },
  { value: 3, label: "March" },
  { value: 4, label: "April" },
  { value: 5, label: "May" },
  { value: 6, label: "June" },
  { value: 7, label: "July" },
  { value: 8, label: "August" },
  { value: 9, label: "September" },
  { value: 10, label: "October" },
  { value: 11, label: "November" },
  { value: 12, label: "December" },
] as const;
