import type { LegalNotice } from "../types";
import { counsel } from "./counsel";

export const mockNotices: LegalNotice[] = [
  {
    id: 601,
    reference: "LN-OUT-2026-0042",
    direction: "outgoing",
    subject: "Payment default — Agrolink Manufacturing",
    counterparty: "Agrolink Manufacturing Pvt. Ltd.",
    status: "sent",
    risk: "high",
    dueDate: "2026-06-25",
    assignedTo: counsel(1),
  },
  {
    id: 602,
    reference: "LN-IN-2026-0018",
    direction: "incoming",
    subject: "Cease and desist — trademark usage",
    counterparty: "BrandGuard Legal Services",
    status: "received",
    risk: "high",
    dueDate: "2026-06-22",
    assignedTo: counsel(1),
  },
  {
    id: 603,
    reference: "LN-OUT-2026-0039",
    direction: "outgoing",
    subject: "Contract termination — SecureLogix",
    counterparty: "SecureLogix Systems",
    status: "responded",
    risk: "medium",
    dueDate: "2026-06-10",
    assignedTo: counsel(3),
  },
  {
    id: 604,
    reference: "LN-IN-2026-0015",
    direction: "incoming",
    subject: "Labour inspector show-cause notice",
    counterparty: "Labour Department, MP",
    status: "received",
    risk: "medium",
    dueDate: "2026-06-28",
    assignedTo: counsel(2),
  },
  {
    id: 605,
    reference: "LN-OUT-2026-0045",
    direction: "outgoing",
    subject: "NDA breach reminder — Innovate Partners",
    counterparty: "Innovate Partners LLP",
    status: "draft",
    risk: "low",
    dueDate: "2026-07-05",
    assignedTo: counsel(2),
  },
  {
    id: 606,
    reference: "LN-IN-2026-0012",
    direction: "incoming",
    subject: "Tax demand notice — GST assessment",
    counterparty: "GST Department",
    status: "closed",
    risk: "low",
    dueDate: "2026-05-30",
    assignedTo: counsel(2),
  },
];
