import type { VendorDispute } from "../types";
import { counsel } from "./counsel";

export const mockVendorDisputes: VendorDispute[] = [
  {
    id: 201,
    vendorName: "CloudHost India Pvt. Ltd.",
    contractRef: "VND-2024-0088",
    status: "negotiation",
    risk: "medium",
    amountInDispute: 185000,
    assignedTo: counsel(1),
    openedAt: "2026-04-01T09:00:00Z",
    summary: "SLA breach — downtime credits disputed for Q1 2026.",
  },
  {
    id: 202,
    vendorName: "PrintMax Solutions",
    contractRef: "VND-2025-0112",
    status: "open",
    risk: "low",
    amountInDispute: 42000,
    assignedTo: counsel(2),
    openedAt: "2026-05-20T10:00:00Z",
    summary: "Invoice mismatch on delivered marketing collateral quantity.",
  },
  {
    id: 203,
    vendorName: "SecureLogix Systems",
    contractRef: "VND-2023-0045",
    status: "arbitration",
    risk: "high",
    amountInDispute: 920000,
    assignedTo: counsel(3),
    openedAt: "2025-09-10T09:00:00Z",
    summary: "Early termination penalty — vendor claims ₹9.2L; arbitration panel constituted.",
  },
  {
    id: 204,
    vendorName: "Office Supplies Co.",
    contractRef: "VND-2025-0201",
    status: "resolved",
    risk: "low",
    amountInDispute: 12500,
    assignedTo: counsel(2),
    openedAt: "2026-02-15T09:00:00Z",
    summary: "Duplicate billing — settled with credit note.",
  },
  {
    id: 205,
    vendorName: "DevTools Licensing AB",
    contractRef: "VND-2024-0156",
    status: "litigation",
    risk: "high",
    amountInDispute: 450000,
    assignedTo: counsel(3),
    openedAt: "2025-12-01T09:00:00Z",
    summary: "License audit — unlicensed seat count dispute escalated to civil suit.",
  },
];
