import { Router, type IRouter } from "express";
import asyncHandler from "express-async-handler";
import { requireAuth, requireRole } from "@/middlewares/auth";
import * as projectsController from "@/controllers/projects.controller";
const router: IRouter = Router();
router.get("/projects", requireAuth, asyncHandler(projectsController.getProjects));
router.post("/projects", requireAuth, requireRole("super_admin"), asyncHandler(projectsController.postProjects));
router.get("/projects/:id", requireAuth, asyncHandler(projectsController.getProjectsById));
router.patch("/projects/:id", requireAuth, requireRole("super_admin"), asyncHandler(projectsController.patchProjectsById));
router.delete("/projects/:id", requireAuth, requireRole("super_admin"), asyncHandler(projectsController.deleteProjectsById));
router.get("/projects/:id/members", requireAuth, asyncHandler(projectsController.getProjectsByIdMembers));
router.post("/projects/:id/members", requireAuth, requireRole("super_admin"), asyncHandler(projectsController.postProjectsByIdMembers));
router.delete("/projects/:id/members/:userId", requireAuth, requireRole("super_admin"), asyncHandler(projectsController.deleteProjectsByIdMembersByUserId));
router.get("/projects/:id/apk-schedules", requireAuth, asyncHandler(projectsController.getProjectsByIdApkSchedules));
router.post("/projects/:id/apk-schedules", requireAuth, requireRole("super_admin"), asyncHandler(projectsController.postProjectsByIdApkSchedules));
router.get("/projects/:id/milestones", requireAuth, asyncHandler(projectsController.getProjectsByIdMilestones));
router.post("/projects/:id/milestones", requireAuth, requireRole("super_admin"), asyncHandler(projectsController.postProjectsByIdMilestones));
router.get("/projects/:id/logs", requireAuth, asyncHandler(projectsController.getProjectsByIdLogs));
router.get("/projects/:id/bugs", requireAuth, asyncHandler(projectsController.getProjectsByIdBugs));
router.get("/projects/:id/apk-releases", requireAuth, asyncHandler(projectsController.getProjectsByIdApkReleases));
router.get("/projects/:id/history", requireAuth, asyncHandler(projectsController.getProjectsByIdHistory));

export default router;
